all:
	mkdir -p build
	cc foo.c -o ../build/foo
	cc fizzbuzz.c -o ../build/fizzbuzz
	cc wc.c -o ../build/wc
	cc nice.c -o ../build/nice
	cc celcius.c -o ../build/celcius
	cc MARK.c -o ../build/MARK
	cc test.c -o ../build/test
	cc small.c -o ../build/small
	cc power.c -o ../build/power
	cc cat.c -o ../build/cat
	cc operator.c -o ../build/operator
